version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: push2prod-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - push2prod-net
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: push2prod-frontend
    ports:
      - "80:80"
    networks:
      - push2prod-net
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: push2prod-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - push2prod-net
    ports:
      - "27017:27017"

networks:
  push2prod-net:
    driver: bridge

volumes:
  mongo_data:
    driver: local
