version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: push2prod-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - push2prod-net

  frontend:
    build:
      context: ./frontend
    container_name: push2prod-frontend
    ports:
      - "80:80"
    networks:
      - push2prod-net
    depends_on:
      - backend

networks:
  push2prod-net:
    driver: bridge
